/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './contentArea.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../about/about.component.ngfactory';
import * as i3 from '../about/about.component';
import * as i4 from './contentArea.component';
const styles_ContentAreaComponent:any[] = [i0.styles];
export const RenderType_ContentAreaComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_ContentAreaComponent,data:{}});
export function View_ContentAreaComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-about',([] as any[]),
      (null as any),(null as any),(null as any),i2.View_AboutComponent_0,i2.RenderType_AboutComponent)),
      i1.ɵdid(49152,(null as any),0,i3.AboutComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export function View_ContentAreaComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'ng-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_ContentAreaComponent_0,
      RenderType_ContentAreaComponent)),i1.ɵdid(49152,(null as any),0,i4.ContentAreaComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const ContentAreaComponentNgFactory:i1.ComponentFactory<i4.ContentAreaComponent> = i1.ɵccf('ng-component',
    i4.ContentAreaComponent,View_ContentAreaComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FubmFiLi9Ecm9wYm94L3BlcnNvbmFsLXdlYnNpdGUvc3JjL2FwcC9jb250ZW50QXJlYS9jb250ZW50QXJlYS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvYW5uYWIuL0Ryb3Bib3gvcGVyc29uYWwtd2Vic2l0ZS9zcmMvYXBwL2NvbnRlbnRBcmVhL2NvbnRlbnRBcmVhLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2FubmFiLi9Ecm9wYm94L3BlcnNvbmFsLXdlYnNpdGUvc3JjL2FwcC9jb250ZW50QXJlYS9jb250ZW50QXJlYS5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2FubmFiLi9Ecm9wYm94L3BlcnNvbmFsLXdlYnNpdGUvc3JjL2FwcC9jb250ZW50QXJlYS9jb250ZW50QXJlYS5jb21wb25lbnQudHMuQ29udGVudEFyZWFDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8YXBwLWFib3V0PjwvYXBwLWFib3V0PiIsIjxuZy1jb21wb25lbnQ+PC9uZy1jb21wb25lbnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTthQUFBO1VBQUE7OztvQkNBQTtNQUFBO3FDQUFBLFVBQUE7TUFBQTs7OyJ9
