/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './about.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../contact/contact.component.ngfactory';
import * as i3 from '../contact/contact.component';
import * as i4 from './about.component';
const styles_AboutComponent:any[] = [i0.styles];
export const RenderType_AboutComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_AboutComponent,data:{}});
export function View_AboutComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),12,'div',[['class',
      'container']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          0,'img',[['alt','...'],['class','img-circle'],['src','assets/Graphics/me.png']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n\n    '])),(_l()(),i1.ɵeld(0,(null as any),
          (null as any),7,'div',[['class','jumbotron']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n        '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),4,'p',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n\n            Hi, I am Anna Buyevich. I am currently a sophomore studying Computer Science and Mathematics at the University of Illinois at Urbana-Champaign. Computer science fascinates me, and I am committed to being a life learner.\n\n\n\n\n            '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-contact',([] as any[]),
          (null as any),(null as any),(null as any),i2.View_ContactComponent_0,i2.RenderType_ContactComponent)),
      i1.ɵdid(49152,(null as any),0,i3.ContactComponent,([] as any[]),(null as any),
          (null as any)),(_l()(),i1.ɵted((null as any),['\n\n        '])),(_l()(),
          i1.ɵted((null as any),['\n\n    '])),(_l()(),i1.ɵted((null as any),['\n\n\n']))],
      (null as any),(null as any));
}
export function View_AboutComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-about',([] as any[]),
      (null as any),(null as any),(null as any),View_AboutComponent_0,RenderType_AboutComponent)),
      i1.ɵdid(49152,(null as any),0,i4.AboutComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const AboutComponentNgFactory:i1.ComponentFactory<i4.AboutComponent> = i1.ɵccf('app-about',
    i4.AboutComponent,View_AboutComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FubmFiLi9Ecm9wYm94L3BlcnNvbmFsLXdlYnNpdGUvc3JjL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvYW5uYWIuL0Ryb3Bib3gvcGVyc29uYWwtd2Vic2l0ZS9zcmMvYXBwL2Fib3V0L2Fib3V0LmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2FubmFiLi9Ecm9wYm94L3BlcnNvbmFsLXdlYnNpdGUvc3JjL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2FubmFiLi9Ecm9wYm94L3BlcnNvbmFsLXdlYnNpdGUvc3JjL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQudHMuQWJvdXRDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XG4gICAgPGltZyBzcmM9XCJhc3NldHMvR3JhcGhpY3MvbWUucG5nXCIgYWx0PVwiLi4uXCIgY2xhc3M9XCJpbWctY2lyY2xlXCI+XG5cbiAgICA8ZGl2IGNsYXNzPVwianVtYm90cm9uXCI+XG4gICAgICAgIDxwPlxuXG4gICAgICAgICAgICBIaSwgSSBhbSBBbm5hIEJ1eWV2aWNoLiBJIGFtIGN1cnJlbnRseSBhIHNvcGhvbW9yZSBzdHVkeWluZyBDb21wdXRlciBTY2llbmNlIGFuZCBNYXRoZW1hdGljcyBhdCB0aGUgVW5pdmVyc2l0eSBvZiBJbGxpbm9pcyBhdCBVcmJhbmEtQ2hhbXBhaWduLiBDb21wdXRlciBzY2llbmNlIGZhc2NpbmF0ZXMgbWUsIGFuZCBJIGFtIGNvbW1pdHRlZCB0byBiZWluZyBhIGxpZmUgbGVhcm5lci5cblxuXG5cblxuICAgICAgICAgICAgPGFwcC1jb250YWN0PjwvYXBwLWNvbnRhY3Q+XG5cbiAgICAgICAgPC9wPlxuXG4gICAgPC9kaXY+XG5cblxuPC9kaXY+IiwiPGFwcC1hYm91dD48L2FwcC1hYm91dD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQXVCLDJDQUNuQjtVQUFBO1VBQUE7TUFBK0QsNkNBRS9EO1VBQUE7VUFBQSw0Q0FBdUI7VUFBQSxpQkFDbkI7VUFBQTtNQUFHO01BT0M7VUFBQTthQUFBO1VBQUEsZUFBMkIsaURBRTNCO2lCQUFBLDhCQUVGOzs7O29CQ2ZWO01BQUE7YUFBQTtVQUFBOzs7In0=
