/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.container[_ngcontent-%COMP%] {\n    \n    display: flex;\n    align-items: center;\n    margin: 10px auto;\n    vertical-align: middle;\n}\n\n.jumbotron[_ngcontent-%COMP%] {\n    \n    display: flex;\n    align-items: center;\n    margin: 10px auto;\n    background: transparent;\n    vertical-align: middle;\n}\n\n.jumbotron[_ngcontent-%COMP%]   p[_ngcontent-%COMP%] {\n    font-size: 2.5rem;\n    font-weight: 600px;\n    font-family: \'Roboto\', sans-serif;\n}\n\np[_ngcontent-%COMP%] {\n    text-align: center;\n    color: #fff;\n    font-weight: 600px;\n    text-shadow: 1px 1px #333;\n    line-height: 115%;\n}\n\n.img-circle[_ngcontent-%COMP%] {\n    align-items: center;\n    border: 1px solid #333;\n    margin: 60px 0px;\n}\n\n@media only screen and (max-device-width: 1000px) {\n    .img-circle[_ngcontent-%COMP%] {\n        height: 200px;\n        margin-top: 180px;\n    }\n}\n\n@media only screen and (max-device-width: 1000px) {\n    .jumbotron[_ngcontent-%COMP%]   p[_ngcontent-%COMP%] {\n        height: 200px;\n        font-size: 1.3rem;\n        margin-top: 180px;\n        width: 190px;\n    }\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FubmFiLi9Ecm9wYm94L3BlcnNvbmFsLXdlYnNpdGUvc3JjL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2FubmFiLi9Ecm9wYm94L3BlcnNvbmFsLXdlYnNpdGUvc3JjL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
