/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['p[_ngcontent-%COMP%] {\n    color: #fff;\n    font-size: 2.5rem;\n}\n\n.link[_ngcontent-%COMP%] {\n    color: #fff;\n}\n\n.link[_ngcontent-%COMP%]:hover {\n    color: #c9302c;\n    border: none;\n}\n\na[_ngcontent-%COMP%] {\n    text-align: right;\n    color: #fff;\n    margin: 10px 5px 5px 5px;\n    padding: 3px;\n}\n\na[_ngcontent-%COMP%]:hover {\n    color: #333;\n    text-shadow: none;\n}\n\n@media only screen and (max-device-width: 1000px) {\n    p[_ngcontent-%COMP%] {\n        height: 50px;\n        font-size: 1.3rem;\n        margin-top: 10px;\n        width: 190px;\n    }\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FubmFiLi9Ecm9wYm94L3BlcnNvbmFsLXdlYnNpdGUvc3JjL2FwcC9jb250YWN0L2NvbnRhY3QuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9hbm5hYi4vRHJvcGJveC9wZXJzb25hbC13ZWJzaXRlL3NyYy9hcHAvY29udGFjdC9jb250YWN0LmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
