/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './contact.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './contact.component';
const styles_ContactComponent:any[] = [i0.styles];
export const RenderType_ContactComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_ContactComponent,data:{}});
export function View_ContactComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),4,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n\n\n    Feel free to contact me at'])),(_l()(),i1.ɵeld(0,
      (null as any),(null as any),1,'a',[['class','link'],['href','mailto:avbuyevich@gmail.com']],
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),[' avbuyevich@gmail.com'])),(_l()(),i1.ɵted((null as any),
      ['\n\n'])),(_l()(),i1.ɵted((null as any),['\n\n'])),(_l()(),i1.ɵeld(0,(null as any),
      (null as any),4,'button',[['class','btn btn-danger'],['type','button']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
      ['\n  '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'a',[['class','resume'],
      ['href','assets/resume.pdf'],['target','_blank']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),['Resume'])),
      (_l()(),i1.ɵted((null as any),['\n']))],(null as any),(null as any));
}
export function View_ContactComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-contact',
      ([] as any[]),(null as any),(null as any),(null as any),View_ContactComponent_0,
      RenderType_ContactComponent)),i1.ɵdid(49152,(null as any),0,i2.ContactComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const ContactComponentNgFactory:i1.ComponentFactory<i2.ContactComponent> = i1.ɵccf('app-contact',
    i2.ContactComponent,View_ContactComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FubmFiLi9Ecm9wYm94L3BlcnNvbmFsLXdlYnNpdGUvc3JjL2FwcC9jb250YWN0L2NvbnRhY3QuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2FubmFiLi9Ecm9wYm94L3BlcnNvbmFsLXdlYnNpdGUvc3JjL2FwcC9jb250YWN0L2NvbnRhY3QuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvYW5uYWIuL0Ryb3Bib3gvcGVyc29uYWwtd2Vic2l0ZS9zcmMvYXBwL2NvbnRhY3QvY29udGFjdC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2FubmFiLi9Ecm9wYm94L3BlcnNvbmFsLXdlYnNpdGUvc3JjL2FwcC9jb250YWN0L2NvbnRhY3QuY29tcG9uZW50LnRzLkNvbnRhY3RDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cD5cblxuXG4gICAgRmVlbCBmcmVlIHRvIGNvbnRhY3QgbWUgYXQ8YSBocmVmPVwibWFpbHRvOmF2YnV5ZXZpY2hAZ21haWwuY29tXCIgY2xhc3M9XCJsaW5rXCI+IGF2YnV5ZXZpY2hAZ21haWwuY29tPC9hPlxuXG48L3A+XG5cbjxidXR0b24gdHlwZT1cImJ1dHRvblwiIGNsYXNzPVwiYnRuIGJ0bi1kYW5nZXJcIj5cbiAgPGEgdGFyZ2V0PVwiX2JsYW5rXCIgaHJlZj1cImFzc2V0cy9yZXN1bWUucGRmXCIgY2xhc3M9XCJyZXN1bWVcIj5SZXN1bWU8L2E+XG48L2J1dHRvbj4iLCI8YXBwLWNvbnRhY3Q+PC9hcHAtY29udGFjdD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBRzthQUFBLDBEQUcyQjtNQUFBO01BQUEsd0VBQW1EO2FBQUEsMkNBQXlCO01BQUEsV0FFdEcseUNBRUo7TUFBQTtNQUFBLDBEQUE2QztNQUFBLFdBQzNDO01BQUE7TUFBQSw0Q0FBMkQ7TUFBVTs7O29CQ1J2RTtNQUFBO2lDQUFBLFVBQUE7TUFBQTs7OyJ9
