/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from './contentArea/contentArea.component.ngfactory';
import * as i4 from './projects/projects.component.ngfactory';
import * as i5 from './skills/skills.component.ngfactory';
import * as i6 from './app.component.ngfactory';
import * as i7 from '@angular/common';
import * as i8 from '@angular/platform-browser';
import * as i9 from '@angular/forms';
import * as i10 from '@angular/http';
import * as i11 from '@angular/router';
import * as i12 from './contentArea/contentArea.component';
import * as i13 from './projects/projects.component';
import * as i14 from './skills/skills.component';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.ContentAreaComponentNgFactory,i4.ProjectsComponentNgFactory,i5.SkillsComponentNgFactory,
              i6.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i7.NgLocalization,
              i7.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(5120,i0.IterableDiffers,
              i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),
          i0.ɵmpd(4608,i8.DomSanitizer,i8.ɵe,[i7.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,
              (null as any),[i8.DomSanitizer]),i0.ɵmpd(4608,i8.HAMMER_GESTURE_CONFIG,
              i8.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,i8.EVENT_MANAGER_PLUGINS,
              (p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i8.ɵDomEventsPlugin(p0_0),new i8.ɵKeyEventsPlugin(p1_0),
                    new i8.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i7.DOCUMENT,i7.DOCUMENT,i7.DOCUMENT,i8.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i8.EventManager,i8.EventManager,[i8.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i8.ɵDomSharedStylesHost,i8.ɵDomSharedStylesHost,[i7.DOCUMENT]),
          i0.ɵmpd(4608,i8.ɵDomRendererFactory2,i8.ɵDomRendererFactory2,[i8.EventManager,
              i8.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,(null as any),
              [i8.ɵDomRendererFactory2]),i0.ɵmpd(6144,i8.ɵSharedStylesHost,(null as any),
              [i8.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,i0.Testability,
              [i0.NgZone]),i0.ɵmpd(4608,i8.Meta,i8.Meta,[i7.DOCUMENT]),i0.ɵmpd(4608,
              i8.Title,i8.Title,[i7.DOCUMENT]),i0.ɵmpd(4608,i9.ɵi,i9.ɵi,([] as any[])),
          i0.ɵmpd(4608,i10.BrowserXhr,i10.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i10.ResponseOptions,
              i10.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i10.XSRFStrategy,
              i10.ɵb,([] as any[])),i0.ɵmpd(4608,i10.XHRBackend,i10.XHRBackend,[i10.BrowserXhr,
              i10.ResponseOptions,i10.XSRFStrategy]),i0.ɵmpd(4608,i10.RequestOptions,
              i10.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,i10.Http,i10.ɵc,[i10.XHRBackend,
              i10.RequestOptions]),i0.ɵmpd(5120,i11.ActivatedRoute,i11.ɵf,[i11.Router]),
          i0.ɵmpd(4608,i11.NoPreloading,i11.NoPreloading,([] as any[])),i0.ɵmpd(6144,
              i11.PreloadingStrategy,(null as any),[i11.NoPreloading]),i0.ɵmpd(135680,
              i11.RouterPreloader,i11.RouterPreloader,[i11.Router,i0.NgModuleFactoryLoader,
                  i0.Compiler,i0.Injector,i11.PreloadingStrategy]),i0.ɵmpd(4608,i11.PreloadAllModules,
              i11.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i11.ROUTER_INITIALIZER,
              i11.ɵi,[i11.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i11.ROUTER_INITIALIZER]),i0.ɵmpd(512,i7.CommonModule,i7.CommonModule,
              ([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i8.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.NgProbeToken,() => {
                return [i11.ɵb()];
              },([] as any[])),i0.ɵmpd(256,i0.APP_ID,'ang4-seo',([] as any[])),i0.ɵmpd(2048,
              i8.ɵTRANSITION_ID,(null as any),[i0.APP_ID]),i0.ɵmpd(512,i11.ɵg,i11.ɵg,
              [i0.Injector]),i0.ɵmpd(1024,i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any,
              p1_1:any,p1_2:any,p2_0:any) => {
            return [i8.ɵc(p0_0,p0_1),i8.ɵf(p1_0,p1_1,p1_2),i11.ɵh(p2_0)];
          },[[2,i8.NgProbeToken],[2,i0.NgProbeToken],i8.ɵTRANSITION_ID,i7.DOCUMENT,
              i0.Injector,i11.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,i0.ApplicationInitStatus,
              [[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,i0.ɵe,[i0.NgZone,i0.ɵConsole,
              i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,i0.ApplicationInitStatus]),
          i0.ɵmpd(2048,i0.ApplicationRef,(null as any),[i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,
              i0.ApplicationModule,[i0.ApplicationRef]),i0.ɵmpd(512,i8.BrowserModule,
              i8.BrowserModule,[[3,i8.BrowserModule]]),i0.ɵmpd(1024,i11.ɵa,i11.ɵd,
              [[3,i11.Router]]),i0.ɵmpd(512,i11.UrlSerializer,i11.DefaultUrlSerializer,
              ([] as any[])),i0.ɵmpd(512,i11.ChildrenOutletContexts,i11.ChildrenOutletContexts,
              ([] as any[])),i0.ɵmpd(256,i11.ROUTER_CONFIGURATION,{},([] as any[])),
          i0.ɵmpd(1024,i7.LocationStrategy,i11.ɵc,[i7.PlatformLocation,[2,i7.APP_BASE_HREF],
              i11.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i7.Location,i7.Location,[i7.LocationStrategy]),
          i0.ɵmpd(512,i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i11.ROUTES,() => {
            return [[{path:'',component:i12.ContentAreaComponent},{path:'projects',
                component:i13.ProjectsComponent},{path:'skills',component:i14.SkillsComponent}]];
          },([] as any[])),i0.ɵmpd(1024,i11.Router,i11.ɵe,[i0.ApplicationRef,i11.UrlSerializer,
              i11.ChildrenOutletContexts,i7.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i11.ROUTES,i11.ROUTER_CONFIGURATION,[2,i11.UrlHandlingStrategy],
              [2,i11.RouteReuseStrategy]]),i0.ɵmpd(512,i11.RouterModule,i11.RouterModule,
              [[2,i11.ɵa],[2,i11.Router]]),i0.ɵmpd(512,i9.ɵba,i9.ɵba,([] as any[])),
          i0.ɵmpd(512,i9.FormsModule,i9.FormsModule,([] as any[])),i0.ɵmpd(512,i10.HttpModule,
              i10.HttpModule,([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FubmFiLi9Ecm9wYm94L3BlcnNvbmFsLXdlYnNpdGUvc3JjL2FwcC9hcHAubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2FubmFiLi9Ecm9wYm94L3BlcnNvbmFsLXdlYnNpdGUvc3JjL2FwcC9hcHAubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
